# cloudbuild.yaml (Corrigido com Logging e Artifact Registry)

timeout: '1600s'
steps:
  # 1. Testar
  - name: 'python:3.9'
    id: Testar
    entrypoint: 'bash'
    args: ['-c', 'pip install -r requirements-dev.txt && pytest tests/']

  # 2. Construir Imagem (Usando Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build-Image
    args:
      - 'build'
      # --- ALTERADO: Caminho do Artifact Registry ---
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'
      - '.'
    waitFor: ['Testar']

  # 3. Enviar Imagem (Usando Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Image
    args:
      # --- ALTERADO: Caminho do Artifact Registry ---
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'
    waitFor: ['Build-Image']

  # 4. Publicar Template RAW (Apontando para Imagem no Artifact Registry)
  - name: 'gcr.io/google-cloud-sdk/google-cloud-sdk'
    id: Publish-Raw-Template
    entrypoint: 'gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://${_BUCKET_TEMPLATES}/templates/hotelaria_raw_pipeline.json'
      # --- ALTERADO: Caminho da Imagem ---
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'
      - '--sdk-language=PYTHON'
      - '--env=FLEX_TEMPLATE_PYTHON_PY_MODULE=hotelaria_pipeline.raw.main_raw'
    waitFor: ['Push-Image']

  # 5. Publicar Template TRUSTED (Apontando para Imagem no Artifact Registry)
  - name: 'gcr.io/google-cloud-sdk/google-cloud-sdk'
    id: Publish-Trusted-Template
    entrypoint: 'gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://${_BUCKET_TEMPLATES}/templates/hotelaria_trusted_pipeline.json'
      # --- ALTERADO: Caminho da Imagem ---
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'
      - '--sdk-language=PYTHON'
      - '--env=FLEX_TEMPLATE_PYTHON_PY_MODULE=hotelaria_pipeline.trusted.main_trusted'
    waitFor: ['Push-Image']

  # 6. Publicar Template REFINED (Apontando para Imagem no Artifact Registry)
  - name: 'gcr.io/google-cloud-sdk/google-cloud-sdk'
    id: Publish-Refined-Template
    entrypoint: 'gcloud'
    args:
      - 'dataflow'
      - 'flex-template'
      - 'build'
      - 'gs://${_BUCKET_TEMPLATES}/templates/hotelaria_refined_pipeline.json'
      # --- ALTERADO: Caminho da Imagem ---
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'
      - '--sdk-language=PYTHON'
      - '--env=FLEX_TEMPLATE_PYTHON_PY_MODULE=hotelaria_pipeline.refined.main_refined'
    waitFor: ['Push-Image']

# Variável de substituição (Configurada no Trigger)
substitutions:
  _BUCKET_TEMPLATES: 'bk-etl-hotelaria' # Valor Padrão (pode ser sobrescrito no trigger)

# Imagem final (Usando Artifact Registry)
images:
  # --- ALTERADO: Caminho do Artifact Registry ---
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/hotelaria-pipelines-repo/hotelaria-pipeline:latest'

# --- ADICIONADO: Configuração de Logging ---
options:
  logging: CLOUD_LOGGING_ONLY
# --- FIM DA ADIÇÃO ---